In [ ]:
# !pip install numpy

In [1]:
import numpy as np  

#np.array() is used to create a NumPy array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Array Properties

In [2]:
import numpy as np

a = np.array([[1, 2, 3, 5], [4, 5, 6, 7],[7,8,9,7]])
print(a.ndim)   # Dimension (2)
print(a.shape)  # Shape (2,3)
print(a.size)   # Total elements (6)

2
(3, 4)
12


List to numpy

In [4]:
import numpy as np
list1 = [1,2,3,4,5]     #Existing list with data.
list2 = [[1,2,3,4],[5,6,7,8]]   #list2 shape(2,4)
c = np.array(list1)  #Creating ndarray from list 
d = np.array(list2)
print(c)
print(d)

# output :
# [1 2 3 4 5]
# [[1 2 3 4]
#  [5 6 7 8]]

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


Array Reshaping

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

# .reshape() is used to change the dimensions
b_reshaped = b.reshape(3, 2)  
print(b_reshaped)   # 2x3 → Reshaped: 3x2

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


Indexing & Slicing

In [8]:
a = np.array([10, 20, 30, 40, 50]) 
print(a[1:4]) # 1,2,3
print(a[1:5:2]) # var[start(0) : stop : step]
# 1,2,3,4 - 1,3 -20,40

# output :
# [20 30 40] 
# [20 40]

[20 30 40]
[20 40]


In [3]:
# Positive indexing

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a[:2,1:4]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4]
 [6 7 8]]


In [19]:
# Negative indexing

import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
y = a[-1:,-1:]
# y = a[-1:1,-1:1]
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[12]]


In [16]:
# Negative Indexing

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[:-2,:-1]  
# ":-2" - strat=0 & stop=(-2) , raw ,12,56,9 10
# ":-1" - start=0 & stop = (-1) , column ,123,567,9 10 11
# : index , "," -raw and column
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]]


data type Conversion

In [10]:
import numpy as np
x=[1,3,4]

# (dtype is data type) TypeCasting : converting int into float
a=np.array(x,dtype=float) 
#Casting : converting int into float
print(a)

# output
# [1. 3. 4.]

[1. 3. 4.]


Ravel Function

In [5]:
import numpy as np 
# a = np.arange(8).reshape(2,4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.ravel()) # [1,2,3,4,5,6,7,8]

# output
# [[0 1 2 3]
#  [4 5 6 7]]
# [0 1 2 3 4 5 6 7]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Numpy Broadcasting

In [13]:
a = np.array([1, 2, 3])
b = 2

# Broadcasts b to match shape of a
print(a * b)  # 1*2 ,2*2, 3*2 

[2 4 6]


Creating Array with Function

In [17]:
# Once()

import numpy as np
e=np.ones((2,2)) #Creates a array of ones
print(e)
print(type(e[0,0]))

# output
# [[1. 1.]
#  [1. 1.]]
# <class 'numpy.float64'>

[[1. 1.]
 [1. 1.]]
<class 'numpy.float64'>


In [20]:
# zeros

import numpy as np
#creates a array of zeros
d=np.zeros((3,3)) 
print(d)
print(type(d[0,0]))

# output :
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]
# <class 'numpy.float64'>

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.float64'>


In [21]:
# eye(n)

import numpy as np
d=np.eye(3)
print(d)

# output
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# full(shape,n)

import numpy as np 
e=np.full((3,4),10)
print(e)

# output
# [[5 5 5 5]
#  [5 5 5 5]
#  [5 5 5 5]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


Random - rand() & randint()

In [23]:
import numpy as np
a = np.random.rand(2, 3)
print(a)
b = np.random.randint(10, 15, (2, 3))
print(b)

# output :
# [[0.56 0.21 0.87]
#  [0.34 0.77 0.09]]
# [[42 13 26]
#  [17 38 49]]

[[0.6769115  0.85469892 0.95751696]
 [0.23328881 0.18208019 0.33295799]]
[[13 12 11]
 [13 14 10]]


Arange function

In [26]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b=np.array([0,2,1,0])
#arange function 
print(a[np.arange(4), b])   #0,1,2,3 & 0,2,1,0 -[1,6,8,10]
#Selected updation of elements from a matrix
a[np.arange(4),b]+=10   
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  8 10]
[[11  2  3]
 [ 4  5 16]
 [ 7 18  9]
 [20 11 12]]


Numpy Math

In [27]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x + y)
print(np.add(x, y))         # Addition
print(x - y)
print(np.subtract(x, y))    # Subtraction
print(x * y)
print(np.multiply(x, y))    # Multiplication
print(x / y)
print(np.divide(x, y))      # Division
print(np.sqrt(x))           # Square root

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Transpose()

In [29]:
import numpy as np
x = np.array([[1,2], [3,4]]) 
print(x) 
#By using T attribute of an array object   
print(x.T) 

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([[1,2,3]])
print(v)
#By using the transpose function
transposed = np.transpose(v) 
print(transposed)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2 3]]
[[1]
 [2]
 [3]]
